equipment = [
    {"price": 1, "name": "10 arrow or bolts", "description": ""},
    {"price": 1, "name": "Backpack", "description": ""},
    {"price": 1, "name": "Ball of String (20’)", "description": ""},
    {"price": 1, "name": "Barrel or Basket", "description": ""},
    {"price": 1, "name": "Bedroll", "description": ""},
    {"price": 1, "name": "Bell", "description": ""},
    {"price": 1, "name": "Belt Pouch", "description": ""},
    {"price": 1, "name": "Blanket", "description": ""},
    {"price": 1, "name": "Bottle or flask", "description": ""},
    {"price": 1, "name": "Bucket", "description": ""},
    {"price": 1, "name": "Buckler (Wooden or Metal)", "description": ""},
    {"price": 1, "name": "Candle", "description": ""},
    {"price": 1, "name": "Chalk (10pcs)", "description": ""},
    {"price": 1, "name": "Crowbar", "description": ""},
    {"price": 1, "name": "Fishing Pole & Tackle", "description": ""},
    {"price": 1, "name": "Flask of Oil", "description": ""},
    {"price": 1, "name": "Gloves", "description": ""},
    {"price": 1, "name": "Hammer and 10 Spikes", "description": "Cannot be used as a weapon"},
    {"price": 1, "name": "Loot Sack", "description": ""},
    {"price": 1, "name": "Pitons (10)", "description": ""},
    {"price": 1, "name": "Quiver (10 arrow or bolt capacity)", "description": ""},
    {"price": 1, "name": "Rain Poncho", "description": ""},
    {"price": 1, "name": "Rope 50’", "description": ""},
    {"price": 1, "name": "Shovel", "description": ""},
    {"price": 1, "name": "Spare Clothes", "description": ""},
    {"price": 1, "name": "Ten Foot Pole", "description": ""},
    {"price": 1, "name": "Tinder Box", "description": ""},
    {"price": 1, "name": "Torches (10)", "description": ""},
    {"price": 1, "name": "Water/Wine Skin", "description": ""},
    {"price": 1, "name": "Whistle", "description": ""},
    {"price": 1, "name": "Wide Brimmed Hat", "description": ""},
    {"price": 1, "name": "Wooden Box", "description": ""},
    {"price": 5, "name": "Bandage", "description": "Heals D4 one time with 24 hours bed rest"},
    {"price": 5, "name": "Basic Lock Pick Set", "description": "Cannot pick locks without tools"},
    {"price": 5, "name": "Chain (10’)", "description": ""},
    {"price": 5, "name": "Food (or dungeon rations) for a week", "description": ""},
    {"price": 5, "name": "Hooded Lantern", "description": "Requires flask of oil and tinder box"},
    {"price": 5, "name": "One Person Tent", "description": ""},
    {"price": 5, "name": "Parchment (one sheet)", "description": "Includes ink and quill"},
    {"price": 5, "name": "Quiver (25 arrow or bolt capacity)", "description": ""},
    {"price": 5, "name": "Holy Water One Vial", "description": "Enough for one small bomb"},
    {"price": 5, "name": "Small Black Powder Clay Bomb Casing", "description": "Grade 1 Black Powder (enough for one small bomb)"},
    {"price": 10, "name": "Ball Bearings (100)", "description": ""},
    {"price": 10, "name": "Caltrops (1lb)", "description": ""},
    {"price": 10, "name": "Harness", "description": ""},
    {"price": 10, "name": "Iron Box", "description": ""},
    {"price": 10, "name": "Locked Gauntlets", "description": ""},
    {"price": 10, "name": "Mirror", "description": ""},
    {"price": 10, "name": "Quiver (50 arrow or bolt capacity)", "description": ""},
    {"price": 10, "name": "Scroll", "description": ""},
    {"price": 10, "name": "Two Person Tent", "description": ""},
    {"price": 10, "name": "Medium Black Powder Clay Bomb Casing", "description": "Grade 2 Black Powder (enough for one small bomb)"},
    {"price": 20, "name": "Animal (Horse, Camel, etc.)", "description": ""},
    {"price": 20, "name": "Flask of Holy Water", "description": "D4 damage to undead if used as missile weapon"},
    {"price": 20, "name": "Four Person Tent", "description": ""},
    {"price": 20, "name": "Large Black Powder Clay Bomb Casing", "description": "Grade 3 Black Powder (enough for one small bomb)"},
    {"price": 20, "name": "Glass Cutter", "description": ""},
    {"price": 40, "name": "Bear Trap", "description": "1d4 damage"},
    {"price": 40, "name": "Manacles (1 pair)", "description": ""},
    {"price": 40, "name": "Riding Horse", "description": ""},
    {"price": 40, "name": "Holy Symbol", "description": ""},
    {"price": 40, "name": "Master Lock Pick Set", "description": "+2 to Rogue roll when picking locks"},
    {"price": 40, "name": "Spyglass", "description": ""},
    {"price": 40, "name": "Grade 4 Black Powder", "description": "Enough for one small bomb"},
    {"price": 50, "name": "Portable Lab", "description": "For Brew Potion"},
    {"price": 50, "name": "Scroll Paper, Scroll Quill, and Scroll Ink", "description": "Enough for one scroll (For Scribe Scroll)"},
    {"price": 50, "name": "Grade 5 Black Powder", "description": "Enough for one small bomb"},
]
